print("Khongkwan Book is now open!")
print("\nกรอกข้อมูล ชื่อ ชื่อหนังสือ วันที่เริ่มยืม และวันที่คืนได้เลยค่ะ")
customer = input("ชื่อผู้ใช้บริการ")
book = input("ชื่อหนังสือ")
borrowing_date = input("วันที่เริ่มยืมหนังสือ")
returning_date = input("วันที่คืนหนังสือ")
print("คุณ ", customer, "\nยืมหนังสือ ", book, "เริ่มยืมหนังสือวันที่ ", borrowing_date, "ต้องคืนหนังสือวันที่ ", returning_date,)
print("\nบันทึกข้อมูลเรียบร้อย ขอบคุณที่ใช้บริการค่ะ")